name: Secret Scan
description: A custom GitHub Action

on:
  pull_request:
    paths:
      - '**/*'  # Scan all files on pull requests

jobs:
  scan-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install detect-secrets

      - name: Run secret scan
        run: |
          detect-secrets scan --all-files --output results.txt

      - name: Upload results
        uses: actions/upload-artifact@v2
        with:
          name: secret-scan-results
          path: results.txt
