name: code scanning
on:
  push:
  pull_request:
    branches: [main]

jobs:
  check-for-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Yelp's detect-secrets
        uses: RobertFischer/detect-secrets-action@v2.0.0
        with:
          DS_ADDL_ARGS: --output txt

      - name: Upload secrets report
        uses: actions/upload-artifact@v2
        with:
          name: secrets-report
          path: 'secrets-report.txt'
          
