name: 'Secret Scan'
description: 'Scan code for secrets using detect-secrets'
inputs:
  output-file:
    description: 'The file to store the scan results'
    required: false
    default: 'results.txt'
runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      uses: actions/checkout@v2
      run: |
       python -m pip install --upgrade pip
       pip install detect-secrets

    - name: Run secret scan
      uses: actions/checkout@v2
      run: |
        detect-secrets scan --all-files --output ${{ inputs.output-file }}

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: secret-scan-results
        path: ${{ inputs.output-file }}
